on:
  push:
    branches: main

jobs:
  build-dash:
    runs-on: ubuntu-latest

    env:
      APP_SECRET: ${{ secrets.APP_SECRET }}
      APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      APP_NAME: ${{ secrets.APP_NAME }}
      GGMAP_STADIAMAPS_API_KEY: ${{ secrets.GGMAP_STADIAMAPS_API_KEY }}

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::rStrava
            any::sf
            any::googlePolylines
            any::ggmap

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create and populate .Renviron file
        run: |
          echo APP_SECRET="APP_SECRET" >> ~/.Renviron
          echo APP_CLIENT_ID="APP_CLIENT_ID" >> ~/.Renviron
          echo APP_NAME="APP_NAME" >> ~/.Renviron
          echo GGMAP_STADIAMAPS_API_KEY="GGMAP_STADIAMAPS_API_KEY" >> ~/.Renviron
        shell: bash

      - name: Build dash
        run: Rscript -e 'source("build-dash.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add calendar_heatmap.png
          git add facet_map.png
          git add oxford_route_map.png
          git commit -m 'Dashboard updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
