on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::rStrava
            any::sf
            any::googlePolylines
            any::ggmap

      - name: Create Renviron
        run: |
          touch .Renviron
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env
          echo APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID }} >> .env
          echo APP_NAME=${{ secrets.APP_NAME }} >> .env
          echo GGMAP_STADIAMAPS_API_KEY=${{ secrets.GGMAP_STADIAMAPS_API_KEY }} >> .env
          cat .env
          
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build dash
        run: Rscript -e 'source("build-dash.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add calendar_heatmap.png
          git add facet_map.png
          git add oxford_route_map.png
          git commit -m 'Dashboard updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
